################################################################################
# 5) snack-frontend Deployment
################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-frontend
  namespace: front
  labels:
    app: snack-frontend
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: snack-frontend
  template:
    metadata:
      labels:
        app: snack-frontend
    spec:
      containers:
      - name: snack-frontend
        image: public.ecr.aws/y6g9k7g1/front:2.0
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: GUESTBOOK_API_ADDR
          value: "snack-backend.back.svc.cluster.local:3000"
---
################################################################################
# 6) snack-frontend Service
################################################################################
apiVersion: v1
kind: Service
metadata:
  name: snack-frontend
  namespace: front
spec:
  selector:
    app: snack-frontend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: NodePort
