apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snack-mongodb-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: "openebs-hostpath"  # 필요한 경우 클러스터에 맞게 변경
